In [1]:
import physics_sim_simple_moreparticles

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as p3
import matplotlib.animation as animation

In [3]:
physics_sim_simple_moreparticles.particles

In [4]:
for pp in physics_sim_simple_moreparticles.particles:
    print(pp)

In [5]:
for pp in physics_sim_simple_moreparticles.particles:
    print(pp.velocity)

[-0.6518911  -1.01698239 -0.79959907]
[-4.00170618  0.37270981 -0.83109186]
[-1.2994569  -1.50200442  1.16046205]
[-1.44645577 -0.10697167  0.95428016]
[ 1.17149561 -0.08868008 -1.7431748 ]
[-1.24152915 -1.01894451 -0.28054667]
[1.50461913 0.69899048 0.77116075]
[ 0.86200807 -1.14342261  0.25549052]
[0.745282   0.51139047 0.12629534]
[ 0.14651171 -0.39365453 -1.78662087]
[-0.1353629   1.33503635  2.17242962]
[-0.97147271  1.07823576 -0.83040151]


In [6]:
particle_list = list(physics_sim_simple_moreparticles.particles)

In [7]:
positions_list = []
times_list = []
groups_list = []
for pp in particle_list:
    position_list = []
    time_list = []
    group_list = []
    for timess, position in enumerate(pp.positions):
        position_list.append(position)
        time_list.append(timess)
        group_list.append(pp.group)
    positions_list.append(position_list)
    times_list.append(time_list)
    groups_list.append(group_list)
    

In [9]:
positions_list

[[array([ 1,  2, -1]),
  array([ 1.,  2., -1.]),
  array([ 1.00275331,  2.00035968, -1.00063643]),
  array([ 1.00484182,  2.00047002, -1.00351045]),
  array([ 1.00452753,  1.99947588, -1.00445122]),
  array([ 1.00296128,  1.99858044, -1.00253421]),
  array([ 0.99988381,  1.99798646, -1.00291001]),
  array([ 0.99945822,  2.00016418, -1.0020369 ]),
  array([ 0.99924239,  2.00136514, -0.99974706]),
  array([ 1.00052289,  2.00289277, -0.99869974]),
  array([ 1.00243201,  2.002653  , -0.99906738]),
  array([ 1.00964434,  2.00453159, -0.9998576 ]),
  array([ 1.01676072,  2.00645561, -1.00061487]),
  array([ 1.023032  ,  2.00365936, -1.00136953]),
  array([ 1.03093097,  1.99942736, -1.00105078]),
  array([ 1.04020231,  1.99564021, -1.0009928 ]),
  array([ 1.0460793,  1.9922405, -1.0013655]),
  array([ 1.05234156,  1.98441736, -1.00144243]),
  array([ 1.05879071,  1.97728116, -1.00238131]),
  array([ 1.06571466,  1.97062153, -1.00321976]),
  array([ 1.07314369,  1.96361224, -1.00484003]),
  ar

In [10]:
len(positions_list)

12

In [11]:
particles_new = positions_list
labels_new = list(range(len(particles_new)))


In [12]:
len(groups_list[-1])

1000

In [23]:
groups_list

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,


In [13]:
for ig, group in enumerate(particles_new):
    print(ig)

0
1
2
3
4
5
6
7
8
9
10
11


In [14]:
particle_labels = []
for ig, group in enumerate(particles_new):
    particle_label_group = []
    for ie, entry in enumerate(group):
        #new_entry = [*entry, labels_new[ig]]
        new_entry = [*entry, groups_list[ig][ie]]
        
        particle_label_group.append(new_entry)
    particle_labels.append(particle_label_group)


In [22]:
particle_label_group

[[0.824256331456545, 1.7194978993507792, -0.6934900984067744, 1],
 [0.824256331456545, 1.7194978993507792, -0.6934900984067744, 1],
 [0.8242961168184209, 1.7168676171795711, -0.6935515353418391, 1],
 [0.8239369866114431, 1.7141156308257153, -0.6909153227297335, 1],
 [0.8232156360397812, 1.708959375279425, -0.6883743277131642, 1],
 [0.8236380074916431, 1.7014086936097155, -0.6849084372030945, 1],
 [0.8258358819692386, 1.6945628980031926, -0.6810054680392567, 1],
 [0.8276816552834924, 1.6886682590501525, -0.6765079104758744, 1],
 [0.8291758795956511, 1.6860980491654287, -0.6738966539126156, 1],
 [0.8312978499987907, 1.681588187683224, -0.6707704988750665, 1],
 [0.8345946360910191, 1.6762883090763971, -0.6684151560056149, 1],
 [0.8383487248103775, 1.6694922073349776, -0.6666978733485338, 1],
 [0.8432908801143714, 1.660920523520139, -0.6625516677466154, 1],
 [0.849069269688829, 1.6525024282763003, -0.6560989666889103, 1],
 [0.8539668681507335, 1.6425311359246673, -0.6499609159869387, 1],
 

In [16]:
particles = particle_labels

In [17]:
times_list

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  15

In [25]:
particles

[[[1, 2, -1, 0],
  [1.0, 2.0, -1.0, 0],
  [1.0027533149204237, 2.0003596817913083, -1.0006364300131803, 0],
  [1.0048418236550247, 2.000470019308595, -1.0035104455305253, 0],
  [1.004527530927681, 1.9994758802161874, -1.0044512249863748, 0],
  [1.0029612804288208, 1.998580438611575, -1.0025342058269078, 0],
  [0.9998838082339269, 1.9979864574271027, -1.0029100081990672, 0],
  [0.9994582212398329, 2.0001641820305633, -1.0020369014124015, 0],
  [0.9992423924909004, 2.001365138055728, -0.9997470637872459, 0],
  [1.0005228923943825, 2.0028927653381743, -0.9986997392474539, 0],
  [1.002432008274751, 2.0026529962489987, -0.9990673764624141, 0],
  [1.0096443448131933, 2.004531594324805, -0.9998576036345306, 0],
  [1.0167607199103126, 2.006455605775121, -1.0006148668318964, 0],
  [1.0230319977591575, 2.003659362847785, -1.0013695264334241, 0],
  [1.0309309716268078, 1.9994273595362857, -1.001050776447913, 0],
  [1.0402023057963294, 1.9956402054014786, -1.0009928022930974, 0],
  [1.046079296777

In [30]:
len(groups_list)

12

In [33]:
len(np.unique(np.array(groups_list).flatten()))

2

In [34]:
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap

'''
partdim = 3
particle1 = data1
particle2 = data2
particles = [particle1, particle2, data3, data4]

particles = particle_labels
'''

viridis = cm.get_cmap('viridis', len(particles))
#label_colors = viridis(np.linspace(0, 1, len(particles)))
label_colors = viridis(np.linspace(0, 1, len(np.unique(np.array(groups_list).flatten()))))


dt = 0.1

%matplotlib notebook
%matplotlib notebook
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

%matplotlib notebook
%matplotlib notebook


def init():
    time_text.set_text('')
    return time_text

particle_lists = [[] for _ in range(len(particles))] 
label_lists = [[] for _ in range(len(particles))]  

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_xlim(-25, 25)
ax.set_ylim(-25, 25)
ax.set_zlim(-25, 25)

ax.set_xlim(np.min(np.array(particles)[:,:,0].flatten()), np.max(np.array(particles)[:,:,0].flatten()))
ax.set_ylim(np.min(np.array(particles)[:,:,1].flatten()), np.max(np.array(particles)[:,:,1].flatten()))
ax.set_zlim(np.min(np.array(particles)[:,:,2].flatten()), np.max(np.array(particles)[:,:,2].flatten()))


scatters = []  
for _ in range(len(particles)):
    scatters.append(ax.scatter([], [], [], marker='o'))

time_template = 'time = %.1f'
time_text = ax.text(0.05, 0.9, 0.9, '', transform=ax.transAxes)

def _update_plot(i):
    
    for j, particle in enumerate(particles):
        
        particle_list = particle_lists[j]
        
        label_list = label_lists[j]
        
        particle_list.clear()  
        label_list.clear()  
        
        newp = []
        newl = []
        for entry in particle:
            newp.append(entry[:3])
            newl.append(entry[-1])
            
        particle_list.append(newp[i])     
        label_list.append(newl[i])
        #particle_list.append(entry[:3]) 
        
        #particle_list.append(particle[i])
        
        #particle_list = particle_lists[j]
        #particle_list.append(particle[i])
        scatters[j]._offsets3d = tuple(zip(*particle_list))
        #scatters[j].set_array(np.array(label_list))
        #scatters[j].set_color([0,1,0,0.5])
        scatters[j].set_color(label_colors[newl[i]])
    time_text.set_text(time_template % (i * dt))


/tmp/ipykernel_25267/1790863804.py:13: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  viridis = cm.get_cmap('viridis', len(particles))


<IPython.core.display.Javascript object>

In [35]:
label_colors

array([[0.267004, 0.004874, 0.329415, 1.      ],
       [0.993248, 0.906157, 0.143936, 1.      ]])

In [38]:
np.array(groups_list).flatten()

array([0, 0, 0, ..., 1, 1, 1])

In [36]:

anim = animation.FuncAnimation(fig, _update_plot,
                               frames=len(particles[0]), interval=1, blit=True, init_func=init)

plt.show()

In [37]:
from IPython.display import HTML
HTML(anim.to_html5_video())

In [21]:
for pp in physics_sim_simple_moreparticles.particles:
    print(pp.group)

0
0
0
1
0
1
0
1
0
1
0
1


In [24]:
particles

[[[1, 2, -1, 0],
  [1.0, 2.0, -1.0, 0],
  [1.0027533149204237, 2.0003596817913083, -1.0006364300131803, 0],
  [1.0048418236550247, 2.000470019308595, -1.0035104455305253, 0],
  [1.004527530927681, 1.9994758802161874, -1.0044512249863748, 0],
  [1.0029612804288208, 1.998580438611575, -1.0025342058269078, 0],
  [0.9998838082339269, 1.9979864574271027, -1.0029100081990672, 0],
  [0.9994582212398329, 2.0001641820305633, -1.0020369014124015, 0],
  [0.9992423924909004, 2.001365138055728, -0.9997470637872459, 0],
  [1.0005228923943825, 2.0028927653381743, -0.9986997392474539, 0],
  [1.002432008274751, 2.0026529962489987, -0.9990673764624141, 0],
  [1.0096443448131933, 2.004531594324805, -0.9998576036345306, 0],
  [1.0167607199103126, 2.006455605775121, -1.0006148668318964, 0],
  [1.0230319977591575, 2.003659362847785, -1.0013695264334241, 0],
  [1.0309309716268078, 1.9994273595362857, -1.001050776447913, 0],
  [1.0402023057963294, 1.9956402054014786, -1.0009928022930974, 0],
  [1.046079296777